name: share_plus
description: Flutter plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
version: 10.1.1
homepage: https://github.com/fluttercommunity/plus_plugins
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/share_plus/share_plus
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/share_plus
topics:
  - share
  - utils

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.share
        pluginClass: SharePlusPlugin
      ios:
        pluginClass: FPPSharePlusPlugin

dependencies:
  flutter:
    sdk: flutter
  share_plus_platform_interface: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.1 <6.0.0"

environment:
  sdk: ">=2.19.3 <3.0.0"
  flutter: ">=3.7.12"
